### ISSUE TITLE
Implement Functionality

### ISSUE THREAD

**Issue by nikhil-RGB** [nikhil-RGB/turing-machine-generator#2]
### To-Dos:
- [x] Add input validators in the TextFormFields of the  Form Widget of the TableScreen.
- [x] Add HashMap entry construction via a constructed Configuration and Behaviour object.
- [x] Ensure the table updates to show added Hashmap entries.
- [x] Add a DropDownButton to accept a Configuration to delete an entry.
- [x] Wrap the DataTable in a SizedBox and a SingleScrollChildView, increase fontsizes for data.
- [x] Implement Exception Handler for process() in Tape.dart

**Comment by nikhil-RGB** [comment]
- The reset functionality for the machine clears its associated hashmap, making it impossible to retain an initial config. - - - When adding a new config, the current config should be set to it if it was the first entry to a blank table
Hashmap being disordered is causing some UX issues
