### ISSUE TITLE
Ease of Use

### ISSUE THREAD

**Issue by nikhil-RGB** [nikhil-RGB/turing-machine-generator#4]
### Tasks

- [x] Wrap DataTable in a SizedBox to prevent it from pushing other elements down when it's size grows with additional entries.
- [x] Add scrollbars(Horizontal and Vertical) for scrolling the table.
- [x] Add a Scrollbar for the tape. <br>

Currently, the tape can be viewed by using the touchpad.
